onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp2_tb/clk
add wave -noupdate /mp2_tb/pmem_resp
add wave -noupdate /mp2_tb/pmem_read
add wave -noupdate /mp2_tb/pmem_write
add wave -noupdate -radix binary /mp2_tb/dut/cache/cache_datapath/mem_rdata
add wave -noupdate /mp2_tb/dut/cache/cache_control/mem_read
add wave -noupdate /mp2_tb/dut/cache/cache_control/mem_write
add wave -noupdate /mp2_tb/pmem_address
add wave -noupdate /mp2_tb/pmem_rdata
add wave -noupdate /mp2_tb/pmem_wdata
add wave -noupdate /mp2_tb/dut/cpu/cpu_control/state
add wave -noupdate /mp2_tb/dut/cpu/cpu_control/next_state
add wave -noupdate /mp2_tb/dut/cpu/cpu_datapath/regfile/data
add wave -noupdate /mp2_tb/dut/cpu/cpu_datapath/pc/data
add wave -noupdate /mp2_tb/dut/cpu/cpu_datapath/opcode
add wave -noupdate -expand /mp2_tb/dut/cpu/cpu_datapath/regfile/data
add wave -noupdate -expand /mp2_tb/dut/cache/cache_datapath/datastore_array_w1/data
add wave -noupdate -expand /mp2_tb/dut/cache/cache_datapath/datastore_array_w2/data
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/clk
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/data
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w1/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w1/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w1/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w1/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w2/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w2/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w2/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_array_w2/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/lru/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_compare_w1/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_compare_w1/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_compare_w1/out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w1/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w1/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w1/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w1/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w1/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w1/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w1/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w1/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w1/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w1/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w1/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w1/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/sel
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/c
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/d
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/e
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/f
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/g
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/h
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w1/out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w1/tag
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w1/waytag
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w1/valid_in
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w1/dirty_in
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w1/hit_out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w1/dirty_out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w1/tag_compare
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_compare_w2/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_compare_w2/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_compare_w2/out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w2/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w2/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w2/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_array_w2/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w2/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w2/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w2/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/valid_array_w2/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w2/write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w2/index
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w2/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/tag_array_w2/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/sel
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/c
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/d
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/e
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/f
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/g
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/h
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_out_mux_w2/out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w2/tag
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w2/waytag
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w2/valid_in
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w2/dirty_in
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w2/hit_out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w2/dirty_out
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/dirty_hit_w2/tag_compare
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_16/sel
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_16/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_16/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_16/f
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_parser/sel
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_parser/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_parser/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_parser/f
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_pmem/sel
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_pmem/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_pmem/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/data_way_mux_128_pmem/f
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_in_mux/sel
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_in_mux/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_in_mux/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_in_mux/f
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/pmem_address_mux/sel
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/pmem_address_mux/a
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/pmem_address_mux/b
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/pmem_address_mux/c
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/pmem_address_mux/d
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/pmem_address_mux/f
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_parser/datain
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_parser/writedata
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_parser/mem_byte_enable
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_parser/offset
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_parser/mem_write
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_parser/dataout
add wave -noupdate /mp2_tb/dut/cache/cache_datapath/datastore_parser/internal_offset
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {503291 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 424
configure wave -valuecolwidth 152
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {19461156 ps} {20028361 ps}
